modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "LGPLv3"
issueTrackerURL = "https://github.com/WildfireRomeo/WildfireFemaleGenderMod/issues"

[[mods]]
    modId = "wildfire_gender"
    version = "${version}"
    displayName = "Wildfire's Female Gender Mod"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/female-gender-forge"
    logoFile = "logo.png"
    credits = "Archl, arcti_cc, Kichura, Powerless001, pupnewfster"
    authors = "WildfireRomeo"
    description = "Allows players to choose what gender they want to be."
    displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.wildfire_gender]]
    modId = "minecraft"
    type = "required"
    versionRange = "${mc_version}"
    side = "BOTH"
[[dependencies.wildfire_gender]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version}"
    side = "BOTH"